version: '3.1'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db:3306/db_compose_crud_java_react -schemas=myschema -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./sql/migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_compose_crud_java_react
      MYSQL_USER: root
      MYSQL_PASSWORD: root



